name: shvirtd-example

include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    env_file:
      - .env.local
    environment:
      DB_PORT: 3306

    networks:
      backend:
        ipv4_address: 172.20.0.5

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always

    env_file:
      - .env.local
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - dbdata:/var/lib/mysql

    networks:
      backend:
        ipv4_address: 172.20.0.10

volumes:
  dbdata:
